package symboltable;

public enum SymbolType {
    CLASSSYMBOL,
    CONNECTIONSYMBOL,
    ENUMERATIONSYMBOL,
    FUNCTIONSYMBOL,
    IMPORTSYMBOL,
    INTERFACESYMBOL,
    PACKAGESYMBOL,
    PRORGRAMSYMBOL,
    VARIABLESYMBOL,
    SYMBOL
}
